config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :announcements
    resources :notifications
    resources :services

    root to: "users#index"
  end
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.haml
%footer.page-footer.text-center.text-md-left.unique-color-dark.pt-0.mt-0
  .top-pink-footer
    .container
      / Grid row
      .row.py-4.d-flex.align-items-center
        / Grid column
        .col-md-6.col-lg-5.text-center.text-md-left.mb-md-0
          %h6.mb-4.mb-md-0.white-text Get connected with us on social networks!
        / Grid column
        / Grid column
        .col-md-6.col-lg-7.text-center.text-md-right
          / Facebook
          %a.p-2.m-2.fa-lg.fb-ic.ml-0
            %i.fab.fa-facebook-f.white-text.mr-lg-4
          / Twitter
          %a.p-2.m-2.fa-lg.tw-ic
            %i.fab.fa-twitter.white-text.mr-lg-4
          / Google +
          %a.p-2.m-2.fa-lg.gplus-ic
            %i.fab.fa-google-plus-g.white-text.mr-lg-4
          / Linkedin
          %a.p-2.m-2.fa-lg.li-ic
            %i.fab.fa-linkedin-in.white-text.mr-lg-4
          / Instagram
          %a.p-2.m-2.fa-lg.ins-ic
            %i.fab.fa-instagram.white-text.mr-lg-4
        / Grid column
      / Grid row
  / Footer Links
  .container.mt-5.mb-4.text-center.text-md-left
    .row.mt-3
      / First column
      .col-md-3.col-lg-4.col-xl-3.mb-5
        %h6.spacing.font-weight-bold
          %strong Company name
        %hr.pink.accent-2.mb-4.mt-0.d-inline-block.mx-auto{:style => "width: 60px;"}/
        %p
          Here you can use rows and columns here to organize your footer content. Lorem ipsum dolor sit amet,
          consectetur
          adipisicing elit.
      / First column
      / Second column
      .col-md-2.col-lg-2.col-xl-2.mx-auto.mb-5
        %h6.spacing.font-weight-bold
          %strong Products
        %hr.pink.accent-2.mb-4.mt-0.d-inline-block.mx-auto{:style => "width: 60px;"}/
        %p
          %a{:href => "#!"} MDBootstrap
        %p
          %a{:href => "#!"} MDWordPress
        %p
          %a{:href => "#!"} BrandFlow
        %p
          %a{:href => "#!"} Bootstrap Angular
      / Second column
      / Third column
      .col-md-3.col-lg-2.col-xl-2.mx-auto.mb-5
        %h6.spacing.font-weight-bold
          %strong Useful links
        %hr.pink.accent-2.mb-4.mt-0.d-inline-block.mx-auto{:style => "width: 60px;"}/
        %p
          %a{:href => "#!"} Your Account
        %p
          %a{:href => "#!"} Become an Affiliate
        %p
          %a{:href => "#!"} Shipping Rates
        %p
          %a{:href => "#!"} Help
      / Third column
      / Fourth column
      .col-md-4.col-lg-3.col-xl-3
        %h6.spacing.font-weight-bold
          %strong Contact
        %hr.pink.accent-2.mb-4.mt-0.d-inline-block.mx-auto{:style => "width: 60px;"}/
        %p
          %i.fas.fa-home.mr-3
          Where ever we are registered
        %p
          %i.fas.fa-envelope.mr-3
          dna@are-awesome.com
        %p
          %i.fas.fa-phone.mr-3
          + 01 234 567 88
      / Fourth column
  / Footer Links
  / Copyright
  .footer-copyright.text-center.py-3
    .container-fluid
      © 2019 Copyright:
      %a{:href => "https://mdbootstrap.com/education/bootstrap/", :target => "_blank"} MDBootstrap.com
  / Copyright


-#%footer.footer.text-muted.bg-light
  .container
    %span
      © #{Date.today.year} Your Company
    %ul.list-inline.mb-0.float-right
      %li.list-inline-item.mr-3= link_to "Terms", terms_path
      %li.list-inline-item.mr-3= link_to "Privacy", privacy_path

app/views/shared/_head.html.haml
%title= Rails.configuration.application_name
%meta{:charset => "utf-8"}/
%meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
= csrf_meta_tags
= csp_meta_tag
= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.scrolling-navbar.white
  .container
    %a.navbar-brand.font-weight-bold.title{:href => "../home/main.html"} DNA
    %button.navbar-toggler{"aria-controls" => "navbarTogglerDemo02", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarTogglerDemo02", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarTogglerDemo02.collapse.navbar-collapse
      %ul.list-unstyled.navbar-nav.mr-auto
        %li.nav-item.dropdown.ml-4.mb-0
          %a#navbarDropdownMenuLink.nav-link.dropdown-toggle.title{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown"} Homepage
          .dropdown-menu{"aria-labelledby" => "navbarDropdownMenuLink"}

        %li.nav-item.dropdown.ml-4
          %a#navbarDropdownMenuLink12.nav-link.dropdown-toggle.title{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown"} Features
          .dropdown-menu{"aria-labelledby" => "navbarDropdownMenuLink"}
            .dropdown-item= link_to 'Repository', '#'
            .dropdown-item= link_to 'Blueprint', '#'
            .dropdown-item= link_to 'Quality Assurance', '#'
            .dropdown-item= link_to 'Defect Management', '#'
        %li.nav-item.ml-4
          .title{"data-offset" => "90"}
            = link_to 'Pricing', '#', class: 'nav-link'
        %li.nav-item.ml-4
          .title{"data-offset" => "90"}
            = link_to 'Documentation', '#', class: 'nav-link'
      / Social Icon
      %ul.navbar-nav.nav-flex-icons
        %li.nav-item
          %a.nav-link
            %i.fab.fa-facebook-f.title
        %li.nav-item
          %a.nav-link
            %i.fab.fa-twitter.title
        %li.nav-item
          %a.nav-link
            %i.fab.fa-instagram.title
        %li.nav-item.ml-3
          %a.btn.pink-gradient.btn-rounded.btn-sm.font-weight-bold{"data-offset" => "90", :href => "#download"}
            = 'Free trial'
          %a.btn.aqua-gradient.btn-rounded.btn-sm.font-weight-bold{"data-offset" => "90", :href => "#download"}
            = 'Log in'

app/views/shared/_notices.html.haml
- flash.each do |msg_type, message|
  %div{:class => "alert #{bootstrap_class_for(msg_type)}"}
    .container
      %button.close{"data-dismiss" => "alert"}
        %span ×
      = message